DROP TABLE IF EXISTS gastos_homogenized;

CREATE TABLE gastos_homogenized AS
SELECT
    "KEY_VALUE",
    UPPER(TRIM(TRANSLATE("NIVEL_GOBIERNO_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU'))) AS nivel_gobierno_nombre,
    UPPER(TRIM("NIVEL_GOBIERNO"))                                                  AS nivel_gobierno,
    UPPER(TRIM(TRANSLATE("SECTOR_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))          AS sector_nombre,
    UPPER(TRIM("SECTOR"))                                                          AS sector,
    UPPER(TRIM(TRANSLATE("PLIEGO_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))          AS pliego_nombre,
    UPPER(TRIM("PLIEGO"))                                                          AS pliego,
    UPPER(TRIM("DEPARTAMENTO_EJECUTORA"))                                          AS departamento_ejecutora,
    UPPER(TRIM(TRANSLATE("DEPARTAMENTO_EJECUTORA_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU'))) AS departamento_ejecutora_nombre,
    UPPER(TRIM("PROVINCIA_EJECUTORA"))                                             AS provincia_ejecutora,
    UPPER(TRIM(TRANSLATE("PROVINCIA_EJECUTORA_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU'))) AS provincia_ejecutora_nombre,
    UPPER(TRIM("DISTRITO_EJECUTORA"))                                              AS distrito_ejecutora,
    UPPER(TRIM(TRANSLATE("DISTRITO_EJECUTORA_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU'))) AS distrito_ejecutora_nombre,
    "SEC_EJEC",
    UPPER(TRIM("EJECUTORA"))                                                       AS ejecutora,
    UPPER(TRIM(TRANSLATE("EJECUTORA_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))       AS ejecutora_nombre,
    UPPER(TRIM("PROGRAMA_PPTO"))                                                   AS programa_ppto,
    UPPER(TRIM(TRANSLATE("PROGRAMA_PPTO_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))   AS programa_ppto_nombre,
    UPPER(TRIM("TIPO_ACT_PROY"))                                                   AS tipo_act_proy,
    UPPER(TRIM(TRANSLATE("TIPO_ACT_PROY_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))   AS tipo_act_proy_nombre,
    UPPER(TRIM("ACT_PROY"))                                                        AS act_proy,
    UPPER(TRIM(TRANSLATE("ACT_PROY_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))        AS act_proy_nombre,
    UPPER(TRIM("COMPONENTE"))                                                      AS componente,
    UPPER(TRIM(TRANSLATE("COMPONENTE_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))      AS componente_nombre,
    UPPER(TRIM("FUNCION"))                                                         AS funcion,
    UPPER(TRIM(TRANSLATE("FUNCION_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))         AS funcion_nombre,
    UPPER(TRIM("DIVISION_FUNCIONAL"))                                              AS division_funcional,
    UPPER(TRIM(TRANSLATE("DIVISION_FUNCIONAL_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU'))) AS division_funcional_nombre,
    UPPER(TRIM("GRUPO_FUNCIONAL"))                                                 AS grupo_funcional,
    UPPER(TRIM(TRANSLATE("GRUPO_FUNCIONAL_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU'))) AS grupo_funcional_nombre,
    UPPER(TRIM("FINALIDAD"))                                                       AS finalidad,
    UPPER(TRIM("META"))                                                            AS meta,
    UPPER(TRIM(TRANSLATE("META_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))            AS meta_nombre,
    UPPER(TRIM("DEPARTAMENTO_META"))                                               AS departamento_meta,
    UPPER(TRIM(TRANSLATE("DEPARTAMENTO_META_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU'))) AS departamento_meta_nombre,
    UPPER(TRIM("FUENTE_FINANC"))                                                   AS fuente_financ,
    UPPER(TRIM(TRANSLATE("FUENTE_FINANC_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))   AS fuente_financ_nombre,
    UPPER(TRIM("FUENTE_FINANC_AGREGADA"))                                          AS fuente_financ_agregada,
    UPPER(TRIM(TRANSLATE("FUENTE_FINANC_AGREGADA_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU'))) AS fuente_financ_agregada_nombre,
    UPPER(TRIM("TIPO_RECURSO"))                                                    AS tipo_recurso,
    UPPER(TRIM(TRANSLATE("TIPO_RECURSO_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))    AS tipo_recurso_nombre,
    UPPER(TRIM("CATEG_GASTO"))                                                     AS categ_gasto,
    UPPER(TRIM(TRANSLATE("CATEG_GASTO_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))     AS categ_gasto_nombre,
    UPPER(TRIM("TIPO_TRANSACCION"))                                                AS tipo_transaccion,
    UPPER(TRIM("GENERICA"))                                                        AS generica,
    UPPER(TRIM(TRANSLATE("GENERICA_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))        AS generica_nombre,
    UPPER(TRIM("SUBGENERICA"))                                                     AS subgenerica,
    UPPER(TRIM(TRANSLATE("SUBGENERICA_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))     AS subgenerica_nombre,
    UPPER(TRIM("SUBGENERICA_DET"))                                                 AS subgenerica_det,
    UPPER(TRIM(TRANSLATE("SUBGENERICA_DET_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU'))) AS subgenerica_det_nombre,
    UPPER(TRIM("ESPECIFICA"))                                                      AS especifica,
    UPPER(TRIM(TRANSLATE("ESPECIFICA_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))      AS especifica_nombre,
    UPPER(TRIM("ESPECIFICA_DET"))                                                  AS especifica_det,
    UPPER(TRIM(TRANSLATE("ESPECIFICA_DET_NOMBRE", 'ÁÉÍÓÚáéíóú', 'AEIOUAEIOU')))  AS especifica_det_nombre,
    -- MONTOS 2022
    CAST(COALESCE(NULLIF("PIA_2022", ''), '0') AS NUMERIC)                AS pia_2022,
    CAST(COALESCE(NULLIF("PIM_2022", ''), '0') AS NUMERIC)                AS pim_2022,
    CAST(COALESCE(NULLIF("CERTIFICADO_2022", ''), '0') AS NUMERIC)        AS certificado_2022,
    CAST(COALESCE(NULLIF("COMPROMETIDO_ANUAL_2022", ''), '0') AS NUMERIC) AS comprometido_anual_2022,
    CAST(COALESCE(NULLIF("COMPROMETIDO_2022", ''), '0') AS NUMERIC)       AS comprometido_2022,
    CAST(COALESCE(NULLIF("DEVENGADO_2022", ''), '0') AS NUMERIC)          AS devengado_2022,
    CAST(COALESCE(NULLIF("GIRADO_2022", ''), '0') AS NUMERIC)             AS girado_2022,
    -- MONTOS 2023
    CAST(COALESCE(NULLIF("PIA_2023", ''), '0') AS NUMERIC)                AS pia_2023,
    CAST(COALESCE(NULLIF("PIM_2023", ''), '0') AS NUMERIC)                AS pim_2023,
    CAST(COALESCE(NULLIF("CERTIFICADO_2023", ''), '0') AS NUMERIC)        AS certificado_2023,
    CAST(COALESCE(NULLIF("COMPROMETIDO_ANUAL_2023", ''), '0') AS NUMERIC) AS comprometido_anual_2023,
    CAST(COALESCE(NULLIF("COMPROMETIDO_2023", ''), '0') AS NUMERIC)       AS comprometido_2023,
    CAST(COALESCE(NULLIF("DEVENGADO_2023", ''), '0') AS NUMERIC)          AS devengado_2023,
    CAST(COALESCE(NULLIF("GIRADO_2023", ''), '0') AS NUMERIC)             AS girado_2023,
    -- MONTOS 2024
    CAST(COALESCE(NULLIF("PIA_2024", ''), '0') AS NUMERIC)                AS pia_2024,
    CAST(COALESCE(NULLIF("PIM_2024", ''), '0') AS NUMERIC)                AS pim_2024,
    CAST(COALESCE(NULLIF("CERTIFICADO_2024", ''), '0') AS NUMERIC)        AS certificado_2024,
    CAST(COALESCE(NULLIF("COMPROMETIDO_ANUAL_2024", ''), '0') AS NUMERIC) AS comprometido_anual_2024,
    CAST(COALESCE(NULLIF("COMPROMETIDO_2024", ''), '0') AS NUMERIC)       AS comprometido_2024,
    CAST(COALESCE(NULLIF("DEVENGADO_2024", ''), '0') AS NUMERIC)          AS devengado_2024,
    CAST(COALESCE(NULLIF("GIRADO_2024", ''), '0') AS NUMERIC)             AS girado_2024,
    -- MONTOS 2025
    CAST(COALESCE(NULLIF("PIA_2025", ''), '0') AS NUMERIC)                AS pia_2025,
    CAST(COALESCE(NULLIF("PIM_2025", ''), '0') AS NUMERIC)                AS pim_2025,
    CAST(COALESCE(NULLIF("CERTIFICADO_2025", ''), '0') AS NUMERIC)        AS certificado_2025,
    CAST(COALESCE(NULLIF("COMPROMETIDO_ANUAL_2025", ''), '0') AS NUMERIC) AS comprometido_anual_2025,
    CAST(COALESCE(NULLIF("COMPROMETIDO_2025", ''), '0') AS NUMERIC)       AS comprometido_2025,
    CAST(COALESCE(NULLIF("DEVENGADO_2025", ''), '0') AS NUMERIC)          AS devengado_2025,
    CAST(COALESCE(NULLIF("GIRADO_2025", ''), '0') AS NUMERIC)             AS girado_2025
    from gastos_raw;